---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: svc-fizzbuzz             # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: svc-fizzbuzz          # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: svc-fizzbuzz
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: svc-fizzbuzz
        image: hugdubois/svc-fizzbuzz:0.0.4_dev
        imagePullPolicy: Always
        ports:
          - containerPort: 8080  # Should match the port number that the Go application listens on
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          # To check if the Pod is ready or not
          httpGet:
            path: /version
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: svc-fizzbuzz             # Name of the resource
spec:
  selector:
    app: svc-fizzbuzz            # Map any pod with name svc-fizzbuzz to this service
  type: LoadBalancer             # If you're deploying on cloud, you can use `type: LoadBalancer`. It will automatically provision a load balancer with the cloud provider that will route traffic to your application.
  ports:                         # Take incoming HTTP requests on port 8080 and forward them to the targetPort of 8080
  - name: http
    port: 8080
    targetPort: 8080
