global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - "cadvisor:8080"

  - job_name: 'svc-fizzbuzz'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - "svc-fizzbuzz:8080"
